version: '3'

services:
  mysql-standalone:
    image: mysql:5.6
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
      MYSQL_USER: sa
      MYSQL_PASSWORD: password

  users-mysql-app:
    image: users-mysql
    ports:
      - '8086:8086'
    restart: always
    depends_on:
      -  mysql-standalone
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:mysql://mysql-standalone:3306/test'
      SPRING_PROFILES_ACTIVE: 'mysql'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://192.168.56.106/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3

